databases:
  - name: yourvalorantanalysis
    databaseName: yourvalorantanalysis
    user: yourvalorantanalysis

services:
  - type: web
    name: yourvalorantanalysis
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn yourvalorantanalysis.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yourvalorantanalysis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4